letter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('welcome/', views.welcome, name='welcome'),
    path('today/', views.today_view, name='today'),
    path('finish/', views.finish_view, name='finish'),
    path('timeout/', views.manager_out_view, name='timeout'),

    path('manager-add/', views.create_manager_view, name='manager-add'),
    path('manager-view/<int:manager_id>/', views.view_manager, name='manager-view'),

    path('centers/', views.view_centers, name='centers'),
    path('centers/<int:center_id>/update/', views.center_edit_view, name='center-edit'),
    path('centers/<int:center_id>/delete/', views.delete_center, name='center-delete'),

    path('users/', views.view_users, name='users'),
    path('users/<int:user_id>', views.view_user, name='user_view'),
    path('add-user/', views.create_user_view, name='add-user'),
]

templates/center/center_update.html
{% extends 'center/view_center.html' %}

{% block center %}

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form class="form-horizontal" method="post" action="{% url 'main:center-edit' center_up.id %}">
                {% csrf_token %}
                    <div class="card-body">
                        <h4 class="card-title"><b>{{ center_up.name }}</b> o'zgartirish.</h4>
                        <div class="form-group row">
                            <label for="id" class="col-sm-3 text-end control-label col-form-label">
                                Bo'lim ID:
                            </label>
                            <div class="col-sm-9">
                                <input type="number" name="number" class="form-control" id="id" value="{{ center_up.id }}" disabled/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-sm-3 text-end control-label col-form-label">
                                Bo'lim nomi:
                            </label>
                            <div class="col-sm-9">
                                <input type="text" name="name" class="form-control" id="name" value="{{ center_up.name }}"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="short" class="col-sm-3 text-end control-label col-form-label">
                                Qisqa nomi:
                            </label>
                            <div class="col-sm-9">
                                <input type="text" name="short" class="form-control" id="short" value="{{ center_up.short }}"/>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="fname" class="col-sm-3 text-end control-label col-form-label">
                                Xodim:
                            </label>
                            <!-- Nazorat kartasining turi:  Тип РКК-->
                            <div class="col-md-9">
                                <label>
                                    <select class="select2 form-select shadow-none"
                                            style="width: 100%; height: 36px" name="user_id">
                                        <option value="{{ center_up.user.id }}">
                                            {{ center_up.user.username }}
                                        </option>
                                        {% for user in users %}
                                            <option value="{{ user.id }}">
                                                {{ user.username }} - {{ user.first_name }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </label>
                            </div>
                        </div>
                    </div>
                    <span class="center" style="margin: 10%;">
                        <input class="btn btn-primary center" type="submit" value="BO'LIMNI SAQLASH">
                    </span>
                    <br>
                </form>
                <br>
            </div>
        </div>
    </div>

{% endblock %}

templates/center/view_center.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle  Tepasi  -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-12 d-flex no-block align-items-center">
                    <h4 class="page-title">
                        Toshkent davlat stomatologiya institutining axborot almashinuv platformasi
                    </h4>
                    <div class="ms-auto text-end">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="#">
                                        Dashboard
                                    </a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Library
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  jami, yangi, jarayonda, bajarilgan, muddati o'tgan  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Sales Cards  -->
            <!-- ============================================================== -->

            <div class="row">
                <!-- Column -->
                <div class="col-md-6 col-lg-3 col-xlg-3">
                    <div class="card card-hover">
                        <div class="box bg-cyan text-center">
                            <h1 class="font-light text-white">
                                <i class="mdi mdi-view-dashboard"></i>
                            </h1>
                            <h6 class="text-white">Barcha hatlar {{ jami }}</h6>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <div class="col-md-6 col-lg-3 col-xlg-3">
                    <div class="card card-hover">
                        <div class="box bg-success text-center">
                            <h1 class="font-light text-white">
                                <i class="mdi mdi-chart-areaspline"></i>
                            </h1>
                            <h6 class="text-white">Bajarilgan {{ bajarilgan }}</h6>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <div class="col-md-6 col-lg-3 col-xlg-3">
                    <div class="card card-hover">
                        <div class="box bg-warning text-center">
                            <h1 class="font-light text-white">
                                <i class="mdi mdi-collage"></i>
                            </h1>
                            <h6 class="text-white">Nazoratda {{ nazoratda }}</h6>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <div class="col-md-6 col-lg-3 col-xlg-3">
                    <div class="card card-hover">
                        <div class="box bg-danger text-center">
                            <h1 class="font-light text-white">
                                <i class="mdi mdi-border-outside"></i>
                            </h1>
                            <h6 class="text-white">Muddati o'tgan {{ muddati_utgan }}</h6>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <!-- Column -->
            </div>
            {% block center %}
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h3 class="card-title text-success">Yangi bo'lim qo'shish</h3>
                                <form action="" class="form-horizontal" method="post">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-4">
                                            <label class="center" for="">
                                                Bo'lim nomi: 
                                            </label>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" name="center_name" class="form-control"
                                                   placeholder="col-md-8"/>
                                        </div>
                                        <div class="col-md-2">
                                            <input type="text" name="center_short" class="form-control"
                                                   placeholder="col-md-4"/>
                                        </div>
                                        <div class="col-md-2">
                                            <button class="btn btn-outline-success col-md-12" type="submit">+ Yangi bo'lim qo'shish</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}
            <!-- ============================================================== -->
            <div class="mt-3">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped" role="progressbar"
                         style="width: 100%" aria-valuenow="10" aria-valuemin="0"
                         aria-valuemax="100">
                    </div>
                </div>
            </div> <!-- Chiziq -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Xatlar</h5>
                            <div class="table-responsive">
                                <table id="zero_config" class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Qisqa:</th>
                                        <th>Nomi:</th>
                                        <th>Xodim F.I.O.</th>
                                        <th>username</th>  <!-- Вид документа -->
                                        <th>Status</th>  <!-- Срок Muddat -->
                                        <th><i class="mdi mdi-settings fs-8"></i></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for center in centers %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'main:center-edit' center.id %}">
                                                    <span class="btn btn-outline-success d-flex align-items-center justify-content-center ">
                                                        {{ center.id }}
                                                    </span>
                                                </a>
                                            </td>
                                            <td>{{ center.short }} </td>
                                            <td>{{ center.name }}</td>
                                            {% if center.user %}
                                                <td>{{ center.user.first_name }} {{ center.user.last_name }}</td>
                                                <td>{{ center.user.username }}</td>
                                                <td>{{ center.user.is_superuser }}</td>
                                            {% else %}
                                                <td> yo'q</td>
                                                <td></td>
                                                <td></td>
                                            {% endif %}
                                            <td>
                                                <a href="{% url 'main:center-edit' center.id %}">
                                                    <button type="button" class="btn btn-cyan btn-sm text-white">
                                                        Edit
                                                    </button>
                                                </a>
                                                <form method="post" action="{% url 'main:center-delete' center.pk %}">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-danger btn-sm text-white"
                                                            onclick="return confirm('Siz haqiqatdan ham {{ center.name }} bo\'limni o\'chirmoqchimisiz?')">
                                                        Delete
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    {% empty %}
                                        <td valign="top" colspan="8" class="dataTables_empty">
                                            Jadvalda ma'lumotlar mavjud emas
                                        </td>
                                    {% endfor %}
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>ID</th>
                                        <th>Qisqa:</th>
                                        <th> Nomi:</th>
                                        <th>Xodim F.I.O.</th>
                                        <th>username</th>  <!-- Вид документа -->
                                        <th>Status</th>  <!-- Срок Muddat -->
                                        <th><i class="mdi mdi-settings fs-8"></i></th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->

        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->

        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->

        <footer class="footer text-center">
            All Rights Reserved by Matrix-admin. Designed and Developed by
            <a href="https://www.wrappixel.com">
                TalantDeveloper
            </a>.
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>


{% endblock %}