letter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('welcome/', views.welcome, name='welcome'),
    path('today/', views.today_view, name='today'),
    path('finish/', views.finish_view, name='finish'),
    path('timeout/', views.manager_out_view, name='timeout'),

    path('manager-add/', views.create_manager_view, name='manager-add'),
    path('manager-view/<int:manager_id>/', views.view_manager, name='manager-view'),

    path('centers/', views.view_centers, name='centers'),
    path('centers/<int:center_id>/update/', views.center_edit_view, name='center-edit'),
    path('centers/<int:center_id>/delete/', views.delete_center, name='center-delete'),

    path('users/', views.view_users, name='users'),
    path('users/<int:user_id>', views.view_user, name='user_view'),
    path('add-user/', views.create_user_view, name='add-user'),
]

templates/user/add_user.html
{% extends 'user/users.html' %}

{% block user %}
    <div class="card">
        <div class="card-body wizard-content">
            <h4 class="card-title">Yangi Xodim qo'shish</h4>
            <h6 class="card-subtitle"></h6>
            <form id="example-form" action="{% url 'main:add-user' %}" class="mt-5" method="post">
                {% csrf_token %}
                <div>
                    <label for="userName">
                        To'liq ismi *
                    </label>
                    <input id="userName" name="full_name" type="text" class="required form-control col-md-6" required/>
                    <label for="userName">
                        Foydalanuvchi nomi *
                    </label>
                    <input id="userName" name="username" type="text" class="required form-control" required/>
                    <label for="password">Parol *</label>
                    <input id="password" name="password" type="password" class="required form-control" required/>
                    <label for="confirm">Parolni qayta yozing *</label>
                    <input id="confirm" name="confirm_password" type="password"
                           class="required form-control" required/>
                    <br>
                    <span class="center" style="display: flex; justify-content: center;">
                        <input class="btn btn-primary center" type="submit" value="Xodim qo'shish">
                    </span>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/user/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Elektron hujjat almashish</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="shortcut icon" type="icon" href="{% static 'images/icons/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/login/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/login/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/login/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login/main.css' %}">
    <!--===============================================================================================-->
</head>
<style>
    .clred {
        color: red !important
    }
</style>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="{% static 'images/logotip.png' %}" alt="IMG">
            </div>
            <form class="login100-form validate-form" method="post" action="{% url 'main:login' %}">
                {% csrf_token %}
                <span class="login100-form-title">
						Elektron xujjat almashuv platformasi
					</span>

                <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                    <input class="input100" type="text" name="username" placeholder="Login">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="Password is required">
                    <input class="input100" type="password" name="password" placeholder="Parol">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="container-login100-form-btn">
                {% csrf_token %}

                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>
                <div class="text-center p-t-136">
                    <a class="txt2" href="https://tsdi.uz/">
                        Toshkent davlat Stomotologiya instituti
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>


    <!--===============================================================================================-->
    <script src="{% static 'js/login/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'js/login/popper.js' %}"></script>
    <script src="{% static 'js/login/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'js/login/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'js/login/tilt.jquery.min.js' %}"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'js/login/main.js' %}"></script>

</body>
</html>

templates/user/user_view.html
{% extends 'user/users.html' %}

{% block user %}
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title mb-0">
                    <a href="{% url 'main:users' %}">
                        <i class="mdi mdi-arrow-left-bold"></i>
                        xodimlar
                    </a>
                </h3>
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Username</th>
                    <th scope="col">{{ user.username }}</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>F.I.O.</td>
                    <td class="text-success">
                        {{ user.first_name }} {{ user.last_name }}
                    </td>
                </tr>
                <tr>
                    <td>Status</td>
                    {% if user.is_superuser %}
                        <td class="text-success font-16">
                            admin
                        </td>
                    {% else %}
                        <td class="text-warning font-16">
                            xodim
                        </td>

                    {% endif %}
                </tr>
                <tr>
                    <td>Bo'lim</td>
                    <td class="text-warning">
                        {% if user_center %}
                            {% for user_cet in user_center %}
                                <a class="text-warning" href="{% url 'main:center-edit' user_cet.id %}">
                                    {{ user_cet.name }}
                                </a>
                            {% endfor %}
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/user/users.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle  Tepasi  -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-12 d-flex no-block align-items-center">
                    <h4 class="page-title">
                        Toshkent davlat stomatologiya institutining axborot almashinuv platformasi
                    </h4>
                    <div class="ms-auto text-end">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="#">
                                        Dashboard
                                    </a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Library
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  jami, yangi, jarayonda, bajarilgan, muddati o'tgan  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Sales Cards  -->
            <!-- ============================================================== -->

            <div class="row">
                <!-- Column -->
                <div class="col-md-6 col-lg-3 col-xlg-3">
                    <div class="card card-hover">
                        <div class="box bg-cyan text-center">
                            <h1 class="font-light text-white">
                                <i class="mdi mdi-view-dashboard"></i>
                            </h1>
                            <h6 class="text-white">Barcha hatlar {{ jami }}</h6>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <div class="col-md-6 col-lg-3 col-xlg-3">
                    <div class="card card-hover">
                        <div class="box bg-success text-center">
                            <h1 class="font-light text-white">
                                <i class="mdi mdi-chart-areaspline"></i>
                            </h1>
                            <h6 class="text-white">Bajarilgan {{ bajarilgan }}</h6>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <div class="col-md-6 col-lg-3 col-xlg-3">
                    <div class="card card-hover">
                        <div class="box bg-warning text-center">
                            <h1 class="font-light text-white">
                                <i class="mdi mdi-collage"></i>
                            </h1>
                            <h6 class="text-white">Nazoratda {{ nazoratda }}</h6>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <div class="col-md-6 col-lg-3 col-xlg-3">
                    <div class="card card-hover">
                        <div class="box bg-danger text-center">
                            <h1 class="font-light text-white">
                                <i class="mdi mdi-border-outside"></i>
                            </h1>
                            <h6 class="text-white">Muddati o'tgan {{ muddati_utgan }}</h6>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <!-- Column -->
            </div>
            
            {% block user %}

            {% endblock %}

            <!-- ============================================================== -->
            <div class="mt-3">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped" role="progressbar"
                         style="width: 100%" aria-valuenow="10" aria-valuemin="0"
                         aria-valuemax="100">
                    </div>
                </div>
            </div> <!-- Chiziq -->

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">

                            <h2 class="card-title">
                                Xodimlar
                                <a class="btn btn-outline-success float-end font-18" href="{% url 'main:add-user' %}">
                                    + yangi xodim qo'shish
                                </a>
                            </h2>
                            <br>
                            <div class="table-responsive">
                                <table id="zero_config" class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>F.I.O.</th>
                                        <th>Username:</th>
                                        <th>Status</th>
                                        <th><i class="mdi mdi-settings fs-8"></i></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for user in users %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'main:user_view' user.id %}">
                                                    <span class="btn btn-outline-success d-flex align-items-center justify-content-center ">
                                                        {{ user.id }}
                                                    </span>
                                                </a>
                                            </td>
                                            <td>{{ user.first_name }} - {{ user.last_name }} </td>
                                            <td>{{ user.username }}</td>
                                            {% if user.is_superuser %}
                                                <td class="text-success font-16">
                                                    admin
                                                </td>
                                            {% else %}
                                                <td class="text-warning font-16">
                                                    xodim
                                                </td>

                                            {% endif %}

                                            <td>
                                                <a href="{% url 'main:user_view' user.id %}">
                                                    <button type="button" class="btn btn-cyan btn-sm text-white">
                                                        Edit
                                                    </button>
                                                </a>
                                                <form method="post" action="{% url 'main:user_view' user.id %}">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-danger btn-sm text-white"
                                                            onclick="return confirm('Siz haqiqatdan ham {{ user.username }} o\'chirmoqchimisiz?')">
                                                        Delete
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    {% empty %}
                                        <td valign="top" colspan="8" class="dataTables_empty">
                                            Jadvalda ma'lumotlar mavjud emas
                                        </td>
                                    {% endfor %}
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>ID</th>
                                        <th>F.I.O.</th>
                                        <th>Username:</th>
                                        <th>Status</th>
                                        <th><i class="mdi mdi-settings fs-8"></i></th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">

                </div>
            </div>
            <!-- ============================================================== -->

        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->

        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->

        <footer class="footer text-center">
            All Rights Reserved by Matrix-admin. Designed and Developed by
            <a href="https://www.wrappixel.com">
                TalantDeveloper
            </a>.
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
{% endblock %}